### ISSUE TITLE
Right Click Harvesting

### ISSUE THREAD

**Issue by MelanX** [MelanX/morexfood#1]
Wanna have the right click harvesting feature. A feature with which you can harvest fully grown crops with just a right click and replant them automatically.

**Comment by EwyBoy** [comment]
Hey, cool mod! Nice to see some new modders. If you need help with this you can look at my src code here. This crop has right-click harvesting with instant planting again.

https://github.com/EwyBoy/Cultivated-Tech/blob/master/src/main/java/com/ewyboy/cultivatedtech/common/blocks/crops/BlockCropScorch.java

**Comment by MelanX** [comment]
thank you! I will look at that and maybe use a few things if it's ok.

**Comment by EwyBoy** [comment]
Yeah, my code is open source for a reason. So other people can use it and hopefully learn something.

**Comment by MelanX** [comment]
ok, I'll do it in within the next days, thank you for open source :D
