### ISSUE TITLE
recipes not showing in JEI

### ISSUE THREAD

**Issue by majijn** [MelanX/morexfood#4]
how do you craft the raw chicken fricassee?
none of the fricassee food recipes show up  (besides the one where you can add rice to it to get the with rice version)
also it might be helpful in the overview page to tell people that they get the new seeds from breaking talll grass (im glad i guessed that right lmao)

**Comment by MelanX** [comment]
really? I try with latest version of JEI and everything works fine. 
JEI: 4.8.5.134
More XFood: 0.2.0.1

![2017-12-07_16 37 00](https://user-images.githubusercontent.com/26039509/33723427-f89fc232-db6c-11e7-922e-aedc51a225ab.png)

added, thank you!

**Comment by majijn** [comment]
can confirm recipe doesnt work for me, im running 
More XFood: 0.2.0.1
JEI: 4.8.5.132
![2017-12-09_08 04 08](https://user-images.githubusercontent.com/18368034/33793399-dd2355f4-dcb7-11e7-9d02-9be2b6ff2464.png)


I'll update to that beta version you're running and see if anything changes.

**Comment by MelanX** [comment]
You have carrot pieces instead of mixed vegetables in your crafting grid

**Comment by majijn** [comment]
oh!!! will try that!

they're still not showing in JEI , even after updating though.

Edit: 
![2017-12-09_08 33 40](https://user-images.githubusercontent.com/18368034/33793669-c16e08a0-dcbb-11e7-97a5-41b7b155dc6a.png)
nope, still dont work.

**Comment by majijn** [comment]
cant get it to work on my end for some reason =/

**Comment by MelanX** [comment]
In a few minutes I start searching on pc.

Do you have Pam's Harvestcraft installed?
If not.. I maybe know what's the problem and know how to solve this :D

**Comment by majijn** [comment]
I dont have pam's.

edit: is it the "listallwater" thing? that's a pam's harvestcraft oredict entry?

**Comment by MelanX** [comment]
yes, that's the problem! Will fix it today

**Comment by MelanX** [comment]
fixed in 0.2.0.2
